carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart , name='cart' ),
    path('agregar',views.add , name='add'),
    path('eliminar',views.remove , name='remove')
]

products/urls.py
from django.urls import path

from . import views

# Con esto se indica que todas estas rutas le pertenecen unicamente a la aplicacion de producto
# y con esto vamos a evitar el conflicto de rutas
app_name = 'products'

urlpatterns=[

    #path('<pk>' , views.ProductDetailView.as_view(),name='product') #id-->llave primaria
    #Ahora vamos buscar <slug por el campo slug que es del tipo slug
    path('search' , views.ProductSearchListView.as_view(),name='search'),
    path('<slug:slug>' , views.ProductDetailView.as_view(),name='product') ,

]

storehiro/urls.py
from django.contrib import admin
from django.urls import path
from products.views import ProductListView
from . import views
from products.views import ProductListView
from django.urls import include

#Para usar las constantes creadas con imagenes
from django.conf.urls.static import static 
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',views.index , name='index'),
    #Con este metodo le indicamos a django que vamos a usar la clase como una vista......
    path('',ProductListView.as_view() , name='index'),
    path('usuarios/logout',views.logout_view , name='logout'),
    path('usuarios/login',views.login_view,name='login'),
    path('usuarios/registro',views.register , name='register'),

    path('productos/' , include('products.urls')),

    path('carrito/',include('carts.urls')),
]
#Vamos a condicionar
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

carts/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
import decimal

#Lista de todas las señales que envia Django.
from django.db.models.signals import pre_save ,post_save

from django.db.models.signals import m2m_changed



# Create your models here.
class Cart(models.Model):

    cart_id = models.CharField(max_length=100,null=False,blank=False,unique=True)

    #UNO A MUCHOS
    user = models.ForeignKey(User , null=True ,blank=True,  on_delete=models.CASCADE)

    #MUCHOS A MUCHOS
    #Recordar que cuando se va generar primero se hace un migrate del cart y cartproduct y luego trabajamos o descomentamos la relacion que hay entre ellos
    products =  models.ManyToManyField(Product,through='CartProduct')
    subtotal = models.DecimalField(default=0.0, max_digits=8,decimal_places=2)
    total = models.DecimalField(default=0.0,max_digits=8 , decimal_places=2)
    created_at=models.DateTimeField(auto_now_add=True)

    FEE = 0.05 #Comision

    def __str__(self):
        return self.cart_id

    def update_totals(self):
        self.update_subtotal()
        self.update_total()
    
    def update_subtotal(self):
        #self.subtotal=sum([product.price for product in self.products.all()])
        self.subtotal = sum([
            cp.quantity*cp.product.price for cp in self.products_related()
        ])
        self.save()

    #Suma el total + una comision
    def update_total(self):
        self.total=self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE))
        self.save()

    def products_related(self):

        #Aqui vamos a colocar la relacion con otro producto
        #Con esta linea vamos obtener todos los productos cartproduct
        #Y los objetos productos en una sola consulta
        #Recordar qe select_related nos evita el uso de all()
        #Ahora obtenermos la misma info con una sola consulta los cartproduct y product
        return self.cartproduct_set.select_related('product')

#Esta clase va heredar de models.Manager
#Cuando creamos un objeto lo que vamos a hacer es asignarle una cantidad 
class CartProductManager(models.Manager):

    #Esta clase va obtener los metodos que uno desea extender
    def create_or_update_quantity(self,cart,product,quantity=1):
        #si el objeto no existe en la base de datos pues procede a crearlo
        object , created = self.get_or_create(cart=cart,product=product)

        if not created:
            #object.quantity += int(quantity)
            quantity = object.quantity + int(quantity)

        #Con esto siempre que se cree o se actualize siempre se va a modificar la cantidad 
        object.update_quantity(quantity)
  
        return object


class CartProduct(models.Model):
    #vamos a definir primero la relacion de un carrito y un producto
    cart = models.ForeignKey(Cart , on_delete=models.CASCADE)
    product=models.ForeignKey(Product , on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects=CartProductManager()

    def update_quantity(self,quantity=1):
        self.quantity = quantity
        self.save()


def set_cart_id(sender,instance,*args,**kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

#
def update_totals(sender,instance,action,*args,**kwargs):
    #vamos a registrar las acciones que nos interesan en cualquiera de esos casos vamos a actualizar los casoss
    if  action == 'post_add' or action=='post_remove' or action=='post_clear':
        instance.update_totals()

def post_save_update_totals(sender,instance,*args,**kwargs):
    instance.cart.update_totals()


#Esto se envía al principio del metodo save() de un modelo.
pre_save.connect(set_cart_id , sender = Cart)
post_save.connect(post_save_update_totals , sender=CartProduct)
#Se envia cuando se cambia un ManyToManyField en un modelo instancia.
#Estrictamente hablando, esta no es una señal de modelo, ya que es enviada
#por ManToManyField , pero dato que complemente el pre_save / post_save y pre_delete /post_delete
#cuando se trata de rastrear cambios en los modelos.
m2m_changed.connect(update_totals , sender=Cart.products.through)

    

carts/views.py
from django.shortcuts import render
from .models import Cart
from .utils import get_or_create_cart
from products.models import Product
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from .models import CartProduct


# Create your views here.
#En las vistas tengo que enviar el argumento o dato que voy a pintar en el template
def cart(request):
    cart = get_or_create_cart(request)
    return render(request , 'carts/cart.html' ,{
        'cart':cart
    } )


def add(request):
    cart = get_or_create_cart(request)
    product = Product.objects.get(pk=request.POST.get('product_id'))

    #El formulario nos envia la cantidad cuyo input es quantity
    #storehiro\carts\templates\carts\snippets\add.html
    #Con esto recupero del formulario
    #                                       es 1 si es que la llave no existe
    quantity = request.POST.get('quantity',1)

    #                           este parametro no es más que un diccionario
    #Con esto podemos agregar la cantidad de un producto a un carrito de compras
    #cart.products.add(product , through_defaults={'quantity':quantity})

    #
    cart_product = CartProduct.objects.create_or_update_quantity(cart=cart
                                                ,product=product
                                                ,quantity=quantity)

    return render(request , 'carts/add.html',{
        'quantity':quantity,
        'cart_product':cart_product,
        'product':product
    })


def remove(request):
    #La excepcion manda un codigo de 500 al cliente indicando que hubo un error en el servidor
    #pagenotfound envia un codigo 404 inidicandole al cliente que hay un recurso no encontrado   

    #Nos permitira obtener un objeto a partir de una excepcion
    #get_object_or_404

    #vamos a obtener el carrito de compras
    cart = get_or_create_cart(request)

    #vamos a obtener el producto bajo la llave product_id
    #product = Product.objects.get(pk=request.POST.get('product_id'))
    product =get_object_or_404(Product ,pk=request.POST.get('product_id'))

    cart.products.remove(product)

    return redirect('carts:cart')    

carts/templates/carts/add.html
{% extends 'base.html' %}
{% load product_extras %} 
{% load cart_extras %}

{% block content %}
    <div class="col-3">
        {% if product.image %}
         <img src="{{product.image.url}}" alt="Imagen del producto" width="200" height="200">
        {% endif %}
    </div> 

    <div class="col">
        <div class="h3 font-weight-bold text-success">
           <!--Producto agregado al carrito de compras-->
           {{ quantity | quantity_add_format }} al carrito
        </div>

        <div class="">
            <a href="{% url 'products:product' product.slug %}">{{ product.title }}</a>
        </div>

        <div class="font-weight-bold text-danger">
            {{ product.price | price_format }}
        </div>

        <div class="mt-2">
            <a href="{% url 'carts:cart' %}" class="btn btn-info">Ver carrito</a>
        </div>

        <div class="mt-2">
            <a href="{% url 'index' %}">Seguir comprando</a>
        </div>

    </div>



{% endblock %}

carts/templates/carts/cart.html
{% extends 'base.html' %}
{% load product_extras %}

{% block content %}
   <!-- <h2>Carrito de compras</h2>
    <h3></h3> -->
    {% if cart.products.exists  %}
    <div class="col-8">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio</th>
                </tr>
            </thead>


            <tbody>
                <!-- products_related es un metodo especificado -->
                {% for cp in cart.products_related %}
                    {% with product=cp.product  %}
                        <tr>
                           <!-- Con esto vamos a enumerar la tabla-->
                           <th>{{ forloop.counter }}</th> 

                           <th>
                                {% if product.image %}
                                    <img src="{{product.image.url}}" alt="Imagen del producto" width="200" height="200">
                                {% endif %}
                           </th>
        
                            <th>
                                <a href="{% url 'products:product' product.slug %}">{{product.title}}</a>
                                {% include 'carts/snippets/remove.html' %}
                            </th>

                            <th>{{ cp.quantity }}</th>

                            <th>
                                <span class="font-weight-bold text-danger">{{product.price | price_format }}</span>
                            </th>
        
                        </tr>
        
                    {% endwith %}
        
                {% endfor %}
            </tbody>

            
        </table>
    </div>

    <div class="col">
        <div class="card">
            <div class="card-body">
                <div class="font-weight-bold">
                    Subtotal({{cart.products.count}}): <span class="text-danger">{{ cart.subtotal | price_format}}</span>
                </div>
                <div class="mt-2">
                    <a href="#" class="btn btn-warning">Proceder al pago</a>
                </div>
            </div>
        </div>
    </div>

    {% else %}
    <div class="col">
        <p class="h3">Tu carrito de compras esta vacio</p>
        <a href="{% url 'index' %}">Seguir comprando</a>
    </div>

    {% endif %}


{% endblock %}