carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart , name='cart' ),
    path('agregar',views.add , name='add'),
    path('eliminar',views.remove , name='remove')
]

storehiro/urls.py
from django.contrib import admin
from django.urls import path
from products.views import ProductListView
from . import views
from products.views import ProductListView
from django.urls import include

#Para usar las constantes creadas con imagenes
from django.conf.urls.static import static 
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',views.index , name='index'),
    #Con este metodo le indicamos a django que vamos a usar la clase como una vista......
    path('',ProductListView.as_view() , name='index'),
    path('usuarios/logout',views.logout_view , name='logout'),
    path('usuarios/login',views.login_view,name='login'),
    path('usuarios/registro',views.register , name='register'),

    path('productos/' , include('products.urls')),

    path('carrito/',include('carts.urls')),
]
#Vamos a condicionar
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}<!--Esto es para poder acceder a los archivos estaticos-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>StoreHiro</title>
   
</head> 
<body>

    {% include 'navbar.html' %}

    <div class="container">

        {% include 'messages.html' %}

        <div class="row mt-3">
            {% block content %}


            {% endblock %}
        </div>
    </div>
    
</body>

<script src="https://kit.fontawesome.com/7efd9e34c5.js"></script>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

            <div class="col">
                <h4 class="text-center" >{{ message }}</h4>

                {% include 'products/snippets/search.html' %}

                <div class="row">
                    {% for product in productos %}
                    <div class="col-3 mt-5">

                        {% include 'products/snippets/product.html' %}
                        
                    </div>
                    {% endfor %}
                </div>
                 
            </div>
                <!--
                <ul class="list-group">
                    {% for product in productos %}
                    <li class="list-group-item" >
                        {{product.title }}
                    <span class="text-success"> ${{ product.price }} </span>

                    </li>
                     {% endfor %}
                </ul>
                -->                
                <!-- <img src="{% static 'images/mochila.png' %}" alt="Imagen de mochila"> -->
               


{% endblock %}



<!--
    {% if product.stock %}
    <span class="text-success">Disponible</span>
    {% else %}
    <span class="text-danger">No disponible</span>            
    {% endif %}
-->

templates/messages.html
{% if messages %}
{% for message in messages %}
    {% if message.tags == 'success' %}

    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" >x</button>
        {{message}}
    </div>

    {% else %}

    <div class="alert alert-danger">
        {{message}}
    </div>

    {% endif %}
 

{% endfor %}
{% endif %}

templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}

<div class="navbar navbar-expand-md bg-dark  navbar-dark">
    <a href="{% url 'index' %}" class="navbar-brand">Store Hiro</a>

    <button type="button" name="button" class="navbar-toggler navbar-toggler-right " data-toggle="collapse" data-target="#navb" >
        <span class="navbar-toggler-icon" ></span>
    </button>

    <div id="navb" class="navbar-collapse collapse hide">

        <ul class="navbar-nav" > 
            <li class="nav-item  {% if request.path == cart %} active {% endif %} ">
                    <a href="{{ cart }}" class="nav-link" >Mi carrito <i class="fas fa-shopping-cart"></i></a>
            </li>
        </ul>



        <ul class="nav navbar-nav ml-auto">

            <!--Solo antes del logeo vas a poder ver login registro-->
            {% if user.is_authenticated %}


            <li class="navbar-item {% if request.path == register %}active{% endif %} ">
                <a href="{{ register }}" class="nav-link">   
                    <i class="fas fa-user-plus"></i> 
                    Registro
                </a>
            </li>


            <li class="navbar-item">
                <a href="{% url 'logout' %}" class="nav-link">
                    <i class="fas fa-sign-in-alt"></i>
                    Loguot
                </a>
            </li>



            {% else %}

            <li class="navbar-item {% if request.path == login %}active{% endif %} "><!--Aqui donde yo puedo identificar y mostrarle al usuario donde esta ubicado-->
                <!-- <a href="{% url 'login' %}" class="nav-link"> -->
                    <a href="{{ login }}" class="nav-link">
                    <i class="fas fa-user"></i>
                    Login
                    </a>
            </li>


            {% endif %}

        </ul>
    </div>

</div>